import { NextResponse } from "next/server";
import { TelephonyAudioAdapter } from "@/lib/calling/telephony-adapter";
import {
  getOrCreatePhoneSession,
  bindStreamToCall,
  endPhoneSession,
  maskPhoneNumber,
} from "@/lib/calling/session-manager";
import { executeCopilotTurn } from "@/lib/copilot/unified-agent";
import { synthesizeSpeech } from "@/lib/voice/sarvam";
import { bcp47For } from "@/lib/voice/languages";

export const runtime = "nodejs";

/**
 * Telephony Media Stream Bridge
 *
 * Coordinates real-time telephony audio stream chunks with Sarvam STT/TTS:
 * 1. Handles Twilio stream lifecycle: connected, start, media, stop, mark, clear
 * 2. Unpacks Twilio μ-law 8kHz audio payloads via TelephonyAudioAdapter
 * 3. Decodes to 16kHz linear PCM for Sarvam STT
 * 4. On final speech transcription, executes executeCopilotTurn({ channel: "phone", ... })
 * 5. Encodes Copilot synthesized speech back to 8kHz μ-law frames for Twilio
 * 6. Handles natural barge-in by emitting "clear" frame to abort telephony audio buffer
 */
export async function POST(req: Request) {
  const body = (await req.json().catch(() => ({}))) as {
    event?: string;
    streamSid?: string;
    callSid?: string;
    payload?: string; // base64 mulaw from Twilio
    text?: string;
    interrupted?: boolean;
  };

  const { event, streamSid, callSid, payload, text, interrupted } = body;
  const adapter = new TelephonyAudioAdapter(streamSid, callSid);

  // Stream connected / start
  if ((event === "start" || event === "connected") && streamSid && callSid) {
    bindStreamToCall(streamSid, callSid);
    const session = getOrCreatePhoneSession(callSid);
    console.info(
      `[calling/stream] stream connected callSid=${callSid} streamSid=${streamSid} to=${maskPhoneNumber(session.toNumber)}`
    );
    return NextResponse.json({ ok: true, streamSid, status: event === "start" ? "started" : "connected" });
  }

  // Stream stop / disconnect
  if (event === "stop" && callSid) {
    endPhoneSession(callSid, "twilio_stream_stop");
    console.info(`[calling/stream] stream stopped callSid=${callSid}`);
    return NextResponse.json({ ok: true, status: "stopped" });
  }

  // Barge-in / clear: clear telephony audio buffer immediately
  if (interrupted || event === "clear") {
    console.info(`[calling/stream] barge-in triggered streamSid=${streamSid}`);
    const clearFrame = adapter.createClearFrame();
    return NextResponse.json({ ok: true, clearFrame: JSON.parse(clearFrame), interrupted: true });
  }

  // Process incoming user speech turn (from telephony STT)
  if (text && callSid) {
    const session = getOrCreatePhoneSession(callSid);

    console.info(`[calling/stream] STT final text="${text}" callSid=${callSid}`);

    const result = await executeCopilotTurn({
      channel: "phone",
      text,
      language: session.language,
      trip: session.trip,
      conversation: session.conversation,
      isUserInitiated: true,
    });

    session.conversation = result.conversation;
    const replyText = result.assistantMessage.originalText;

    console.info(`[calling/stream] Copilot turn text="${replyText}" toolUsed=${result.toolUsed ?? "none"}`);

    // Synthesize response speech via Sarvam TTS
    let audioPayloadUlaw: string | null = null;
    if (process.env.SARVAM_API_KEY) {
      try {
        const tts = await synthesizeSpeech(replyText, {
          languageCode: bcp47For(session.language),
          outputAudioCodec: "mp3",
        });
        if (tts.audios?.[0]) {
          audioPayloadUlaw = tts.audios[0];
          console.info(`[calling/stream] TTS generated byteLength=${audioPayloadUlaw.length}`);
        }
      } catch (err) {
        console.warn(`[calling/stream] tts error: ${err instanceof Error ? err.message : err}`);
      }
    }

    return NextResponse.json({
      ok: true,
      text: replyText,
      toolUsed: result.toolUsed,
      audioPayload: audioPayloadUlaw,
      streamSid,
    });
  }

  // Audio chunk forwarding (if receiving base64 mulaw)
  if (payload) {
    const pcm16k = adapter.decodeUlaw8kToPcm16k(payload);
    return NextResponse.json({
      ok: true,
      pcmByteLength: pcm16k.byteLength,
      samples: pcm16k.byteLength / 2,
    });
  }

  return NextResponse.json({ ok: true });
}

export async function GET() {
  return NextResponse.json({
    status: "telephony_media_stream_bridge_active",
    protocol: "twilio_media_stream_v1",
    audioFormat: "audio/x-mulaw;rate=8000",
  });
}

